#基础配置
server:
  port: 8080

# Minio配置
minio:
  # minio服务所在的目标ip
  endpoint: http://192.168.1.1:9000
  # 登录时的账户
  accessKey: ROOTNAME
  # 密码
  secretKey: CHANGEME123
  # 存储的桶
  bucketName: note

### docker配置
#server:
#  port: ${port}
## Minio配置
#minio:
#  # minio服务所在的目标ip
#  endpoint: ${minio_url}
#  # 登录时的账户
#  accessKey: ${minio_user}
#  # 密码
#  secretKey: ${minio_password}
#  # 存储的桶
#  bucketName: ${minio_bucket}
